/**
 * Rafti brand art, generated by `scripts/build-brand-art.py` from the raw renders.
 * Metro needs static requires, so every file is listed.
 */
export const BRAND = {
  /** Rafti's face as a die-cut sticker (transparent). Default avatar, call sticker, splash. */
  sticker: require('./rafti-sticker.png'),
  /** Rafti peering into an empty box (transparent). Empty lists. */
  empty: require('./rafti-empty.png'),
  /** Rafti holding a glowing shell in confetti, on cream. Daily reward. */
  reward: require('./rafti-reward.jpg'),
  /** Two Raftis in a bath of hearts, on cream. Level-up. */
  levelUp: require('./rafti-levelup.jpg'),
  /** Wide Home banner, Rafti on the right. */
  banner: require('./banner-home.jpg'),
  /** Rafti floating asleep on a night sea. Bedtime hero. */
  bedtime: require('./bedtime-scene.jpg'),
  /** Heartbeat Diary cover, 3:4, top third left empty for the title. */
  diaryCover: require('./diary-cover.jpg'),
} as const;

export type BrandArtName = keyof typeof BRAND;

/** Home launcher tiles; the rounded tile is part of the image. Keyed by `HomeModule.key`. */
export const TILES = {
  store: require('./tile-store.png'),
  dating: require('./tile-dating.png'),
  diary: require('./tile-diary.png'),
  photo: require('./tile-photo.png'),
  contacts: require('./tile-contacts.png'),
  radio: require('./tile-radio.png'),
  gifts: require('./tile-gifts.png'),
  calls: require('./tile-calls.png'),
  board: require('./tile-board.png'),
  bedtime: require('./tile-bedtime.png'),
} as const;

export type TileName = keyof typeof TILES;

/**
 * Soft 3D clay icons (transparent), cut from one Nano Banana sheet by the build
 * script. The app's icon style for feature entry points; see docs/icons-3d.md for
 * where each one goes next.
 */
export const CLAY_ICONS = {
  voice: require('./icon3d-voice.png'),
  photo: require('./icon3d-photo.png'),
  secretNote: require('./icon3d-secret-note.png'),
  quiz: require('./icon3d-quiz.png'),
  truthOrDare: require('./icon3d-truth-or-dare.png'),
  date: require('./icon3d-date.png'),
  calls: require('./icon3d-calls.png'),
  diary: require('./icon3d-diary.png'),
  ball: require('./icon3d-ball.png'),
  planner: require('./icon3d-planner.png'),
  play: require('./icon3d-play.png'),
  playStack: require('./icon3d-play-stack.png'),
  gift: require('./icon3d-gift.png'),
  store: require('./icon3d-store.png'),
  contacts: require('./icon3d-contacts.png'),
  radio: require('./icon3d-radio.png'),
  board: require('./icon3d-board.png'),
  bedtime: require('./icon3d-bedtime.png'),
  camera: require('./icon3d-camera.png'),
  calendar: require('./icon3d-calendar.png'),
  search: require('./icon3d-search.png'),
  compass: require('./icon3d-compass.png'),
  music: require('./icon3d-music.png'),
  lock: require('./icon3d-lock.png'),
} as const;

export type ClayIconName = keyof typeof CLAY_ICONS;

/** Rafti reaction stickers, in menu order. Cut from one sheet by the build script. */
export const REACTION_STICKERS = {
  love: require('./reaction-love.png'),
  laugh: require('./reaction-laugh.png'),
  wow: require('./reaction-wow.png'),
  sad: require('./reaction-sad.png'),
  hyped: require('./reaction-hyped.png'),
  thumbs: require('./reaction-thumbs.png'),
} as const;

export type ReactionName = keyof typeof REACTION_STICKERS;

/** Intrinsic width / height, so art can be sized from one dimension. */
export const BRAND_ASPECT: Record<BrandArtName, number> = {
  sticker: 604 / 539,
  empty: 720 / 498,
  reward: 720 / 657,
  levelUp: 800 / 530,
  banner: 1200 / 514,
  bedtime: 1200 / 656,
  diaryCover: 672 / 900,
};
