/**
 * Rafti brand art, generated by `scripts/build-brand-art.py` from the raw renders.
 * Metro needs static requires, so every file is listed.
 */
export const BRAND = {
  /** Rafti's face as a die-cut sticker (transparent). Default avatar, call sticker, splash. */
  sticker: require('./rafti-sticker.png'),
  /** Rafti peering into an empty box (transparent). Empty lists. */
  empty: require('./rafti-empty.png'),
  /** Rafti holding a glowing shell in confetti, on cream. Daily reward. */
  reward: require('./rafti-reward.jpg'),
  /** Two Raftis in a bath of hearts, on cream. Level-up. */
  levelUp: require('./rafti-levelup.jpg'),
  /** Wide Home banner, Rafti on the right. */
  banner: require('./banner-home.jpg'),
  /** Rafti floating asleep on a night sea. Bedtime hero. */
  bedtime: require('./bedtime-scene.jpg'),
  /** Heartbeat Diary cover, 3:4, top third left empty for the title. */
  diaryCover: require('./diary-cover.jpg'),
} as const;

export type BrandArtName = keyof typeof BRAND;

/** Home launcher tiles; the rounded tile is part of the image. Keyed by `HomeModule.key`. */
export const TILES = {
  store: require('./tile-store.png'),
  dating: require('./tile-dating.png'),
  diary: require('./tile-diary.png'),
  photo: require('./tile-photo.png'),
  contacts: require('./tile-contacts.png'),
  radio: require('./tile-radio.png'),
  gifts: require('./tile-gifts.png'),
  calls: require('./tile-calls.png'),
  board: require('./tile-board.png'),
  bedtime: require('./tile-bedtime.png'),
} as const;

export type TileName = keyof typeof TILES;

/** Intrinsic width / height, so art can be sized from one dimension. */
export const BRAND_ASPECT: Record<BrandArtName, number> = {
  sticker: 604 / 539,
  empty: 720 / 498,
  reward: 720 / 657,
  levelUp: 800 / 530,
  banner: 1200 / 514,
  bedtime: 1200 / 656,
  diaryCover: 672 / 900,
};
