/**
 * Wide character scenes for the Today hero card, looked up by character id.
 * Generated by scripts/build-brand-art.py from `hero_<name>.png/` renders; characters
 * without one fall back to their portrait.
 */
export const HEROES: Record<string, number> = {
  c_adrian: require('./c_adrian.jpg'),
  c_aurelian: require('./c_aurelian.jpg'),
  c_castor: require('./c_castor.jpg'),
  c_cole: require('./c_cole.jpg'),
  c_dex: require('./c_dex.jpg'),
  c_elio: require('./c_elio.jpg'),
  c_ezra: require('./c_ezra.jpg'),
  c_felix: require('./c_felix.jpg'),
  c_gideon: require('./c_gideon.jpg'),
  c_hana: require('./c_hana.jpg'),
  c_haze: require('./c_haze.jpg'),
  c_hugo: require('./c_hugo.jpg'),
  c_iris: require('./c_iris.jpg'),
  c_jun: require('./c_jun.jpg'),
  c_juno: require('./c_juno.jpg'),
  c_kai: require('./c_kai.jpg'),
  c_kiro: require('./c_kiro.jpg'),
  c_lucas: require('./c_lucas.jpg'),
  c_lyra: require('./c_lyra.jpg'),
  c_marco: require('./c_marco.jpg'),
  c_minu: require('./c_minu.jpg'),
  c_orin: require('./c_orin.jpg'),
  c_rhys: require('./c_rhys.jpg'),
  c_rowan: require('./c_rowan.jpg'),
  c_seraphine: require('./c_seraphine.jpg'),
  c_seren: require('./c_seren.jpg'),
  c_sol: require('./c_sol.jpg'),
  c_theo: require('./c_theo.jpg'),
  c_vesper: require('./c_vesper.jpg'),
  c_zarek: require('./c_zarek.jpg'),
};
