/**
 * Wide character scenes for the Today hero card, looked up by character id.
 * Generated by scripts/build-brand-art.py from `hero_<name>.png/` renders; characters
 * without one fall back to their portrait.
 */
export const HEROES: Record<string, number> = {
  c_adrian: require('./c_adrian.jpg'),
  c_aurelian: require('./c_aurelian.jpg'),
  c_castor: require('./c_castor.jpg'),
  c_elio: require('./c_elio.jpg'),
  c_ezra: require('./c_ezra.jpg'),
  c_hana: require('./c_hana.jpg'),
  c_iris: require('./c_iris.jpg'),
  c_kai: require('./c_kai.jpg'),
  c_kiro: require('./c_kiro.jpg'),
  c_lucas: require('./c_lucas.jpg'),
  c_minu: require('./c_minu.jpg'),
  c_seraphine: require('./c_seraphine.jpg'),
  c_seren: require('./c_seren.jpg'),
  c_sol: require('./c_sol.jpg'),
  c_theo: require('./c_theo.jpg'),
  c_zarek: require('./c_zarek.jpg'),
};
