/**
 * Seed character portraits (2D anime-style originals), looked up by character id.
 * Generated by scripts/build-brand-art.py from `avatar_<name>.png/` renders; characters
 * without one render a pastel monogram. User-created characters use `avatarUri`.
 */
export const AVATARS: Record<string, number> = {
  c_adrian: require('./c_adrian.png'),
  c_aurelian: require('./c_aurelian.png'),
  c_castor: require('./c_castor.png'),
  c_elio: require('./c_elio.png'),
  c_ezra: require('./c_ezra.png'),
  c_hana: require('./c_hana.png'),
  c_iris: require('./c_iris.png'),
  c_kai: require('./c_kai.png'),
  c_kiro: require('./c_kiro.png'),
  c_lucas: require('./c_lucas.png'),
  c_minu: require('./c_minu.png'),
  c_seraphine: require('./c_seraphine.png'),
  c_seren: require('./c_seren.png'),
  c_sol: require('./c_sol.png'),
  c_theo: require('./c_theo.png'),
  c_zarek: require('./c_zarek.png'),
};
